name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-build.txt
        
    - name: Download ChromeDriver
      run: |
        python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
        
    - name: Build executable
      run: |
        pyinstaller --clean --onefile `
          --add-data "data.json;." `
          --add-data ".env;." `
          --hidden-import selenium `
          --hidden-import webdriver_manager `
          --hidden-import pandas `
          --name "X-Engagement-Tracker" `
          main.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: X-Engagement-Tracker
        path: dist/X-Engagement-Tracker.exe